export const BIZ_TABLE_GET_REQ = 'BIZ_TABLE_GET_REQ';

export const BIZ_TABLE_GET_RES_SUCCESS = 'BIZ_TABLE_GET_RES_SUCCESS';

export const BIZ_TABLE_GET_RES_FAIL = 'BIZ_TABLE_GET_RES_FAIL';

export const BIZ_TABLE_PARAMS_UPDATE = 'BIZ_TABLE_PARAMS_UPDATE';

export const BIZ_TABLE_RELOAD = 'BIZ_TABLE_RELOAD';